targets:
  $default:
    builders:
      auto_route_generator|autoRouteGenerator:
        enabled: true
        generate_for:
          - "**/app_router.dart"

      injectable_generator:injectable_builder: 
        enabled: true
        generate_for:
          - "**/repositories/**.dart"
          - "**/services/**.dart"
          - "**/contracts/**.dart"
          - "**/api/**.dart"
          - "**/config/**"
          - "**/**_bloc.dart"
          - "**/**_vm.dart"
          - "**/**_presenter.dart"
          - "**/**_services.dart"
          - "**/**_mock.dart"
          - "**/**_impl.dart"
          - "**/**_service.dart"
          - "**/remote/**.dart"
          - "**/local/**.dart"

      injectable_generator|injectable_config_builder:
        enabled: true
        generate_for:
          - "**/config/**"


      retrofit_generator|retrofit:
        enabled: true
        options:
          nullsafety: true
        generate_for:
          - "**/api/**.dart"

      json_serializable|json_serializable:
        options:
          checked: true
          explicit_to_json: true
          include_if_null: false
        generate_for:
          - "**/dto/**.dart"
          - "**/entity/**.dart"
          - "**/responses/**.dart"

      freezed|freezed:
        options: 
          makeCollectionsUnmodifiable: false
        generate_for:
          - "**/dto/**.dart"
          - "**/entity/**.dart"
          - "**/responses/**.dart"
          - "**/**_service.dart"
          - "**_bloc.dart"
          - "**_event.dart"
          - "**_state.dart"

