name: architecture
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Helpers
  intl: 0.17.0
  logger: 1.1.0
  google_fonts: 3.0.1
  url_launcher: 6.1.7
  connectivity_plus: 3.0.2
  sentry_flutter: 6.18.2
  pretty_dio_logger: 1.2.0-beta-1

  # UI
  flutter_svg: 1.1.6
  cupertino_icons: 1.0.5
  easy_localization: 3.0.1

  # Http & Generation
  dio: 4.0.6
  get_it: 7.2.0
  freezed: 2.3.2
  retrofit: 3.3.1
  injectable: 2.1.0
  auto_route: 5.0.4
  json_annotation: 4.8.0
  
  # Architecture
  rxdart: 0.27.7
  provider: 6.0.5
  flutter_bloc: 8.1.1
  flutter_dotenv: 5.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: 2.3.3
  json_serializable: 6.6.0
  auto_route_generator: 5.0.3
  retrofit_generator: 4.2.0
  injectable_generator: 2.1.3
  flutter_launcher_icons: 0.11.0
  freezed_annotation: 2.2.0

flutter:
  uses-material-design: true

  assets:
    - .local/
    - assets/svg/
    - assets/icons/